kind: pipeline
name: static-tests

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8
- name: pylint
  image: cytopia/pylint:latest-0.5
  commands:
  - pylint app.py

---
kind: pipeline
name: publish

depends_on:
- static-tests

concurrency:
  limit: 1

trigger:
  status:
  - success
  event:
  - push
  - tag


steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/image-classification-service
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/image-classification-service
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: integration-tests

depends_on:
- publish

concurrency:
  limit: 1

steps:
- name: run tests
  image: python:3.7.6-buster
  pull: always

  commands:
  - apt-get update -yqq
  - apt-get install ffmpeg libsm6 libxext6  -y 
  - pip install pipenv > /dev/null
  - pipenv install --system --deploy --ignore-pipfile
  - ./download_models.sh
  - pytest
  environment:
    OBJECT_DETECTION_ENABLED: true
    OBJECT_DETECTION_MODEL: "yolo"
    IMAGE_CLASSIFICATION_ENABLED: true
    IMAGE_CLASSIFICATION_MODEL: "mobilenet"
    VECTOR_GENERATION_ENABLED: true

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
